config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'enterprises#index'
  resources :enterprises do
    resources :claims, only: [:create]
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :enterprise
  belongs_to :user
end

app/models/enterprise.rb
class Enterprise < ApplicationRecord
  has_many :claims
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :claims
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController

  def create
    @claim = Claim.new
    @claim.title = params[:claim][:title]
    @claim.content = params[:claim][:content]
    @claim.enterprise = Enterprise.find(params[:enterprise_id])
    @claim.user = current_user
    @claim.save
  end
end

app/controllers/enterprises_controller.rb
class EnterprisesController < ApplicationController
  before_action :set_enterprise, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show]

  # GET /enterprises
  # GET /enterprises.json
  def index
    @enterprises = Enterprise.order(created_at: :desc)
    @enterprise = Enterprise.new
  end

  # GET /enterprises/1
  # GET /enterprises/1.json
  def show
    @claims = @enterprise.claims.order(created_at: :desc)
    @claim = Claim.new
  end

  # GET /enterprises/new
  def new
    @enterprise = Enterprise.new
  end

  # GET /enterprises/1/edit
  def edit
  end

  # POST /enterprises
  # POST /enterprises.json
  def create
    @enterprise = Enterprise.new(enterprise_params)

    respond_to do |format|
      if @enterprise.save
        format.html { redirect_to @enterprise, notice: 'Enterprise was successfully created.' }
        format.json { render :show, status: :created, location: @enterprise }
        format.js { render :create, status: :created }
      else
        format.html { render :new }
        format.json { render json: @enterprise.errors, status: :unprocessable_entity }
        format.js { render :error, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /enterprises/1
  # PATCH/PUT /enterprises/1.json
  def update
    respond_to do |format|
      if @enterprise.update(enterprise_params)
        format.html { redirect_to @enterprise, notice: 'Enterprise was successfully updated.' }
        format.json { render :show, status: :ok, location: @enterprise }
        format.js {}

      else
        format.html { render :edit }
        format.json { render json: @enterprise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enterprises/1
  # DELETE /enterprises/1.json
  def destroy
    if @enterprise.claims.any?
      @enterprise.claims.destroy_all
    else
      @enterprise.destroy
    end
    respond_to do |format|
      format.html { redirect_to enterprises_url, notice: 'Enterprise was successfully destroyed.' }
      format.json { head :no_content }
      format.js { }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enterprise
      @enterprise = Enterprise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enterprise_params
      params.require(:enterprise).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/enterprises_helper.rb
module EnterprisesHelper
end

app/views/claims/_claim.html.erb
<div>
  <p>
    <%= @claim.title %>
  </p>
  <p>
  <%= @claim.content %>
</p>
</div>

app/views/claims/create.js.erb
$('#enterprise_claim').prepend("<%= j render 'claim' %>")

app/views/enterprises/_enterprise.html.erb
<tr id='<%="row_#{enterprise.id}"%>'>
    <td id="enterprise_<%= enterprise.id %>"><%= enterprise.name %></td>
    <td><%= link_to 'Ver', enterprise %></td>
    <td><%= link_to 'Editar', edit_enterprise_path(enterprise), class: 'edit_enterprise', data: { remote: true } %></td>
    <td><%= link_to 'Eliminar', enterprise, class: "delete_enterprise", method: :delete, data: { remote: true } %></td>
</tr>

app/views/enterprises/_form.html.erb
<%= form_with(model: enterprise, local: true) do |form| %>
  <% if enterprise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enterprise.errors.count, "error") %> prohibited this enterprise from being saved:</h2>

      <ul>
      <% enterprise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enterprises/_modal.html.erb
<div class="modal" tabindex="-1" role="dialog" id='myModal'>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: @enterprise, id:'edit_form', method: :patch) do |form| %>
      <div class="modal-header">
        <h5 class="modal-title"><%= @enterprise.name%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
            <div class="field">
              <%= form.label :name %>
              <%= form.text_field :name %>
             </div>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <%= form.submit 'Editar', class: 'btn btn-primary', id:'edit_btn' %>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/enterprises/create.js.erb
$('#enterprises').prepend('<%= j render @enterprise %>')

app/views/enterprises/destroy.js.erb
$("#row_<%=@enterprise.id%>").fadeOut(1000)

app/views/enterprises/edit.js.erb
$('#myModal').remove()
$('body').append('<%= j render "modal", enterprise: @enterprise %>')
$('#myModal').modal()

app/views/enterprises/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6">
      <h2>Empresas</h2>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody id='enterprises'>
          <%= render @enterprises %>
        </tbody>
      </table>
  </div>
  <div class="col-md-6">
    <h4>Crear nueva empresa</h4>
    <%= form_with(model: @enterprise) do |form| %>
    <div class="field">
      <%= form.label 'Nombre empresa:' %>
      <%= form.text_field :name %>
    </div>
    <div class="actions">
      <%= form.submit 'Crear empresa', class:'btn btn-success' %>
    </div>
    <% end %>
  </div>
</div>

app/views/enterprises/new.html.erb
<h1>New Enterprise</h1>

<%= render 'form', enterprise: @enterprise %>

<%= link_to 'Back', enterprises_path %>

app/views/enterprises/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <p>
    <strong>Name:</strong>
    <%= @enterprise.name %>
  </p>
  <div class="col-md-6" id='enterprise_claim'>
    <% @claims.each do |claim| %>
    <p>
      <%= claim.title %>
    </p>
    <p>
    <%= claim.content %></p>
    <% end %>
  </div>
  <div class="col-md-6">
    <%= form_with(model: [@enterprise, @claim]) do |form| %>
    <div class="field">
      <%= form.label 'Título reclamo:' %>
      <%= form.text_field :title %>
      <br>
      <%= form.label 'Reclamo:' %>
      <%= form.text_area :content %>
    </div>
    <div class="actions">
      <%= form.submit 'Dejar reclamo', class:'btn btn-success' %>
    </div>
    <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_enterprise_path(@enterprise) %> |
<%= link_to 'Back', enterprises_path %>

app/views/enterprises/update.js.erb
$('#enterprise_<%=@enterprise.id%>').html('<%= @enterprise.name %>')
$('#myModal').modal('hide');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaAjax</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Home', root_path, class:'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if current_user != nil %>
      <li class="nav-item">
          <%= link_to current_user.email, '#', class:'nav-link disabled' %>
        </li>
        <li class='nav-item'>
          <%= link_to 'cerrar sesión', destroy_user_session_path, method: :delete, class:'nav-link'%>
        </li>
        <% else %>
        <li class='nav-item'>
          <%= link_to 'Iniciar sesión', new_user_session_path, class:'nav-link'%>
        </li>

        <% end %>
    </ul>
  </div>
</nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>